# 1. Tensors in Pytorch

In [1]:
import torch

## Tensors in Pytorch

We create some data as list of lists. In particular we create a 2x2 array by creating a list of two lists, each of length two.

In [2]:
my_data = [[1,2], [3,4]] # 2x2 matrix/array

A Tensor is a multi-dimensional matrix containing elements of a single data type. In our case, we are going to use the 2x2 matrix to create a tensor.
A tensor can be constructed from a Python list or sequence using the `torch.tensor()` constructor, as follows:


In [3]:
torch.tensor(my_data)

tensor([[1, 2],
        [3, 4]])

In [4]:
my_tensor = torch.tensor(my_data)
my_tensor.dtype

torch.int64

In [5]:
my_tensor.type()

'torch.LongTensor'

In [6]:
my_tensor.device

device(type='cpu')

Whenever possible, we can allocate the tensor to GPUs. With Google colab, GPUs are free, so that you can perform faster computations with respect to local machines that do not have GPUs. To allocate a tensor to GPU, apply the `to('cuda')` method to the tensor.

In [7]:
my_tensor.to('cuda')

tensor([[1, 2],
        [3, 4]], device='cuda:0')

### Ways of building a tensor
There are many ways of building a tensor. For instance, you can build a tensor from scratch with either zeros or ones, as follows: in case you need a 2x2 tensor,  just pass a tuple made of (2,2)

In [8]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

or with ones

In [9]:
torch.ones((2,2)) # 2x2 matrix/array

tensor([[1., 1.],
        [1., 1.]])

Let us consider the following tensor

In [10]:
new_tensor = torch.ones((2,2))

In [11]:
new_tensor.dtype

torch.float32

In [12]:
new_tensor.type()

'torch.FloatTensor'

In [13]:
updated_new_tensor = new_tensor.new_tensor(my_data)

In [14]:
updated_new_tensor

tensor([[1., 2.],
        [3., 4.]])

we see that now the tensor has been updated in its values. Why should i use the `new_tensor` method? Tensors are array/matrix that contains data placed on either cpu or gpus memory, and have some properties. Sometimes you do not want to change this properties, but you just want to hereditate such properties while updating the data. The `new_tensor` allows to reach this goal with a simple line of code.

In [15]:
updated_new_tensor.dtype

torch.float32

We can even specify the device

In [16]:
another_tensor = torch.zeros((2,2), dtype=torch.int8, device='cuda') 

In [17]:
another_tensor.device

device(type='cuda', index=0)

The nice thing of the `new_tensor` is that you can even create a new tensor starting from the one you just created, but with different data: To create a tensor with similar type but different size as another tensor, use tensor.new_* creation ops.

In [18]:
new_data = [[1,2], [3,4], [5,6]]
another_tensor.new_tensor(new_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], device='cuda:0', dtype=torch.int8)

Finally, we can create a tensor with random values using the `torch.rand()` method, as follows:

In [19]:
# this creates a 2x3 matrix of floats between 0 and 1
shape = (2,3,)
my_tensor = torch.rand(shape)

We can create directly from another tensor using the class of `*_like` as follows: the new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

To create a tensor with the same size (and similar types) as another tensor, use torch.*_like tensor creation ops (see Creation Ops).

In [20]:
x_rand = torch.rand_like(my_tensor, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.9254, 0.1945, 0.5678],
        [0.7718, 0.3628, 0.3090]]) 



**End Lecture 2**