# Tensors in PyTorch - Part 2

In [1]:
import torch

In [2]:
import numpy as np
numpy_data = np.random.rand(2,3)

In [3]:
numpy_data

array([[0.69180835, 0.98459508, 0.23837632],
       [0.52753154, 0.52007687, 0.88052612]])

In [4]:
torch_numpy = torch.from_numpy(numpy_data)

In [5]:
torch_numpy

tensor([[0.6918, 0.9846, 0.2384],
        [0.5275, 0.5201, 0.8805]], dtype=torch.float64)

In [6]:
tensor_numpy_direct = torch.tensor(numpy_data)

In [7]:
tensor_numpy_direct

tensor([[0.6918, 0.9846, 0.2384],
        [0.5275, 0.5201, 0.8805]], dtype=torch.float64)

In [8]:
tensor_numpy_direct.cpu().numpy()

array([[0.69180835, 0.98459508, 0.23837632],
       [0.52753154, 0.52007687, 0.88052612]])

## Operations between tensors

In [9]:
numpy_data = np.random.rand(2,3)

In [10]:
numpy_data

array([[0.84756281, 0.98849891, 0.58002658],
       [0.5328962 , 0.30875801, 0.6163787 ]])

In [11]:
my_tns2 = torch.tensor(numpy_data)

In [12]:
my_tns2

tensor([[0.8476, 0.9885, 0.5800],
        [0.5329, 0.3088, 0.6164]], dtype=torch.float64)

In [13]:
my_tns1 = torch_numpy

In [14]:
my_tns1

tensor([[0.6918, 0.9846, 0.2384],
        [0.5275, 0.5201, 0.8805]], dtype=torch.float64)

In [15]:
torch.cat([my_tns1, my_tns2], dim=1)

tensor([[0.6918, 0.9846, 0.2384, 0.8476, 0.9885, 0.5800],
        [0.5275, 0.5201, 0.8805, 0.5329, 0.3088, 0.6164]], dtype=torch.float64)

In [16]:
my_tns2.clip(0.3, 0.7)

tensor([[0.7000, 0.7000, 0.5800],
        [0.5329, 0.3088, 0.6164]], dtype=torch.float64)

In [17]:
my_tns1.mul(my_tns2)

tensor([[0.5864, 0.9733, 0.1383],
        [0.2811, 0.1606, 0.5427]], dtype=torch.float64)

In [18]:
my_tns1 * my_tns2

tensor([[0.5864, 0.9733, 0.1383],
        [0.2811, 0.1606, 0.5427]], dtype=torch.float64)

In [19]:
my_tns1.matmul(my_tns2.T)

tensor([[1.6979, 0.8196],
        [1.4719, 0.9844]], dtype=torch.float64)

In [20]:
my_tns1 @ my_tns2.T

tensor([[1.6979, 0.8196],
        [1.4719, 0.9844]], dtype=torch.float64)

In [21]:
my_sum = my_tns2.sum()

In [22]:
my_sum

tensor(3.8741, dtype=torch.float64)

In [23]:
my_sum.item()

3.8741212111624868

In [24]:
type(my_sum.item())

float

In [25]:
matrix_A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [26]:
matrix_A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [27]:
matrix_B = matrix_A.clone()

In [28]:
matrix_B + matrix_A

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [29]:
matrix_B.mean()

tensor(9.5000)

In [30]:
matrix_B.mean(dim=0)

tensor([ 8.,  9., 10., 11.])

In [31]:
matrix_B.sum(axis=0)/ matrix_B.shape[0]

tensor([ 8.,  9., 10., 11.])

**End Lecture 3**