# The Autograd Module

In [18]:
import torch

In [19]:
x = torch.tensor([-1.2365, 1.8245, -1.0701, 0.0869, -0.0376])

In [20]:
loss =  x**2 -5


In [21]:
loss

tensor([-3.4711, -1.6712, -3.8549, -4.9924, -4.9986])

In [22]:
x = torch.tensor([-1.2365, 1.8245, -1.0701, 0.0869, -0.0376], requires_grad=True)

In [23]:
loss = x **2 - 5

In [24]:
loss

tensor([-3.4711, -1.6712, -3.8549, -4.9924, -4.9986], grad_fn=<SubBackward0>)

In [25]:
loss.grad_fn

In [26]:
loss.backward(gradient=torch.ones(5))

In [27]:
x.grad

tensor([-2.4730,  3.6490, -2.1402,  0.1738, -0.0752])

$$\frac{\partial y}{\partial x} = 2x$$

In [28]:
2 * x

tensor([-2.4730,  3.6490, -2.1402,  0.1738, -0.0752], grad_fn=<MulBackward0>)

In [29]:
a = torch.rand(2,2, requires_grad=True)

In [30]:
a.requires_grad

True

In [31]:
b = a.detach()

In [32]:
b.requires_grad

False

In [33]:
c = torch.rand(2,2, requires_grad=True)

In [34]:
with torch.no_grad():
  loss = c **2
  print(loss.requires_grad)

False


**End Lecture 04**